### ISSUE TITLE
Cookie containing JSON does not appear to get a valid signature

### ISSUE THREAD

**Issue by oalders** [ap/Plack-Middleware-SignedCookies#1]
First off, thanks for your work on this.  :)

I had some issues with this module yesterday.  I'm having trouble distilling this down to a simple test case to demonstrate hear, so I figure I'll just open an issue to see if it's even worth looking into.

I've got a Mojo app that uses `Plack::Middleware::SignedCookies`.  I was setting a cookie from Mojo.  It was going out fine, but `Plack::Middleware::SignedCookies` was preventing this same cookie from appearing in subsequent requests to the Mojo app.  Once I switched the content of the cookie from JSON to key/value pairs `foo=bar&baz=quz` I no longer had any issues with the module.  

Here's a sample of what I was seeing.  The first cookie (`mm_session`) was making it back in the request, but the second (`ppa`) was not:

Response Cookie:

```
.-----------+-------------------------------------------------------------------------------------.
| Key       | Value                                                                               |
+-----------+-------------------------------------------------------------------------------------+
| key       | mm_session                                                                          |
| val       | 7e8257d6a7a0b526f3ebef79e9085727bfccf10b07lHYRF5l4wAIKpKIax~JN3lOHpxAhwZBBhRaEYyeD8 |
| path      | /                                                                                   |
| domain    | localhost.local                                                                     |
| path_spec | 1                                                                                   |
| expires   | 2017-08-03T19:43:55                                                                 |
'-----------+-------------------------------------------------------------------------------------'

Response Cookie:

.-----------+--------------------------------------------------------------------------------------------------------------.
| Key       | Value                                                                                                        |
+-----------+--------------------------------------------------------------------------------------------------------------+
| key       | ppa                                                                                                          |
| val       | "{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}"Nv1AqiKbuSiODwJcWQmGmV9wHOGrOEChzb9YcUsrRLw |
| path      | /                                                                                                            |
| domain    | localhost.local                                                                                              |
| path_spec | 1                                                                                                            |
| expires   | 2017-07-27T19:48:55                                                                                          |
'-----------+--------------------------------------------------------------------------------------------------------------'
```

The one thing that strikes me is the missing `~` in the `ppa` cookie.  Once I changed the format of the cookie content, the `~` was there.  eg `RESPMSG=Secure+token+already+used.&RESULT=160ltD~1yIlu3e7YVMk1vS0JLbHqDSaaOWDDXBLwQPhxWU`

I was using Mojo's `cookie()` method rather than `signed_cookie()`.

**Comment by ap** [comment]
Glad you like it. 😊

The `~` is merely a stand-in for `/` in the Base64 encoding of the HMAC code… it seems unlikely that its presence has anything to do with the problem.

One thing that strikes me is that the JSON cookie value appears to possibly contain literal `,` characters when you use JSON – which SignedCookies expects to be delimiters in the request header. That seems like a possible culprit in a quick skim of the code.

But that’s just a shot in the dark. The info you’ve given me is not enough to reproduce your issue and figure out what’s going wrong with confidence.

Ideally you could provide me with a minimal app that exhibits the problem.

But I can also construct a test case with just sample data, if you can give me the following:

1. A known value for the HMAC secret, so I can reproduce your HMAC codes.
2. A raw dump of the `Set-Cookie` response header, obtainable e.g. using `curl -IX GET`, with and without SignedCookies.
3. A raw dump of the `Cookie` request header from before and after SignedCookies does its thing, obtainable e.g. with an ad-hoc middleware like this under Plack::Builder (inserted on both sides of SignedCookies):

     ```perl
     enable sub { my $app = shift; sub { warn $_[0]{'HTTP_COOKIE'}; &$app } };
     ```

**Comment by ap** [comment]
> But that’s just a shot in the dark.

Starting to look like a pretty good shot, though:
https://github.com/kraih/mojo/blob/v7.37/lib/Mojo/Cookie/Response.pm#L38

If that’s the reason for the bug you’re seeing, the question would be whose bug it is. My sense is that Mojo does it wrong – as corroborated by
https://github.com/kazeburo/Cookie-Baker/blob/0.08/lib/Cookie/Baker.pm#L36
I’m pretty sure URI-escaping is the correct quoting mechanism here.

However, I’m not yet clear on whether [RFC&#160;6265](https://tools.ietf.org/html/rfc6265) supports my notion. A first read does not conform to my expectations, and I may have been wrong.

(Real raw data or a minimal demonstration would, again, be useful.)

**Comment by oalders** [comment]
@ap thanks so much for the timely response.  :)  I think this is the simplest app I can put together to demonstrate the problem.

```
package MyApp;

use Mojolicious::Lite;

get '/' => sub {
    my $c = shift;

    my $request_cookie = $c->cookie('ppa');

    $c->cookie(
        'ppa' => '{"RESPMSG":"Secure token already used.","RESULT":"160"}' );

    $c->render(
        text => $request_cookie
        ? 'got cookie ' . $request_cookie
        : 'no cookie in request'
    );
};

sub to_app {
    app->secrets( ['Tempus fugit'] );
    app->start;
}

package main;

use strict;
use warnings;

use Plack::Builder;

use lib 'lib';

my $app = MyApp->to_app;

builder {
    enable(
        'Plack::Middleware::SignedCookies',
        secret => 's333333333kr1t!!!!1!!'
    );
    $app;
};
```

I fired this up via `plackup my-app.pl` and tested it with Chrome.  With the middleware disabled, it  get a request cookie.  With it enabled, no cookie makes it back to the app.

Now, the raw dump with middleware enabled:

```
MaxMind-MacBook:cookie olaf$ curl -IX GET http://0:5000
HTTP/1.0 200 OK
Date: Mon, 31 Jul 2017 20:54:51 GMT
Server: HTTP::Server::PSGI
Content-Length: 20
Date: Mon, 31 Jul 2017 20:54:51 GMT
Content-Type: text/html;charset=UTF-8
Set-Cookie: ppa="{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}"tv4-TbOSGrL-M0TZ2e40FbVmrVZtqdYS1ZUGR63kiBA; HTTPonly
```

The raw dump with middleware disabled:

```
MaxMind-MacBook:cookie olaf$ curl -IX GET http://0:5000
HTTP/1.0 200 OK
Date: Mon, 31 Jul 2017 20:56:37 GMT
Server: HTTP::Server::PSGI
Date: Mon, 31 Jul 2017 20:56:37 GMT
Content-Length: 20
Content-Type: text/html;charset=UTF-8
Set-Cookie: ppa="{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}"
```

The raw dump from the middleware anon sub which you provided. With middleware enabled:

```
ppa="{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}"tv4-TbOSGrL-M0TZ2e40FbVmrVZtqdYS1ZUGR63kiBA at /Users/olaf/Documents/maxmind/cookie/my-app.pl line 37.
[Mon Jul 31 16:58:51 2017] [debug] GET "/"
[Mon Jul 31 16:58:51 2017] [debug] Routing to a callback
[Mon Jul 31 16:58:51 2017] [debug] 200 OK (0.000415s, 2409.639/s)
127.0.0.1 - - [31/Jul/2017:16:58:51 -0400] "GET / HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
ppa="{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}"tv4-TbOSGrL-M0TZ2e40FbVmrVZtqdYS1ZUGR63kiBA at /Users/olaf/Documents/maxmind/cookie/my-app.pl line 37.
127.0.0.1 - - [31/Jul/2017:16:58:51 -0400] "GET /favicon.ico HTTP/1.1" 200 - "http://0.0.0.0:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
```

With middleware disabled:

```
ppa="{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}" at /Users/olaf/Documents/maxmind/cookie/my-app.pl line 37.
[Mon Jul 31 17:02:01 2017] [debug] GET "/"
[Mon Jul 31 17:02:01 2017] [debug] Routing to a callback
[Mon Jul 31 17:02:01 2017] [debug] 200 OK (0.000619s, 1615.509/s)
127.0.0.1 - - [31/Jul/2017:17:02:01 -0400] "GET / HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
ppa="{\"RESPMSG\":\"Secure token already used.\",\"RESULT\":\"160\"}" at /Users/olaf/Documents/maxmind/cookie/my-app.pl line 37.
127.0.0.1 - - [31/Jul/2017:17:02:01 -0400] "GET /favicon.ico HTTP/1.1" 200 - "http://0.0.0.0:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
```

**Comment by ap** [comment]
Thank you! Much appreciated. I’ll be taking a look in a day or two.

**Comment by ap** [comment]
Looks like I plain and simply got the Cookie header parser wrong. It should never have split the header value on commas, if I read [the RFC](https://tools.ietf.org/html/rfc6265) correctly. Not sure how that happened, since I’ve read the very same RFC before, when I was first implementing this.

Looking to see if I can find cookie test data to swipe in some browser’s test suite or some such; no luck on that front yet.

Sorry I dropped the ball on this so badly. Hope to have a fix out in a few days.

**Comment by ap** [comment]
https://github.com/curl/curl/blob/master/tests/data/test31

Not very comprehensive…

**Comment by ap** [comment]
This looks promising: https://github.com/abarth/http-state/tree/master/tests/data/parser

Also, https://inikulin.github.io/cookie-compat/

**Comment by ap** [comment]
@oalders: Can you try installing from the `tmp` branch and tell me how that’s looking for you?

**Comment by oalders** [comment]
@ap I just checked out the branch and ran the following script against the simple app I posted above:

```perl
use strict;
use warnings;
use feature qw( say );

use WWW::Mechanize;

my $mech = WWW::Mechanize->new;
my $url = 'http://localhost:5000';

$mech->get($url);
say $mech->text;
$mech->get($url);
say $mech->text;
```

The output was:

```
olaf$ perl mech.pl
no cookie in request
got cookie {"RESPMSG":"Secure token already used.","RESULT":"160"}
```

When I run the same script against master I get:

```
olaf$ perl mech.pl
no cookie in request
no cookie in request
```

So, it looks good to me!  Thanks for all of your work on this.

**Comment by ap** [comment]
Just the releng left. Will do that later today.

**Comment by ap** [comment]
Well, that uncovered some more bugs related to cookie parsing, in this case in old Cookie::Baker versions. Worked around those too.

So it’s now on its way to CPAN. Share and enjoy.

**Comment by oalders** [comment]
Thanks so much for this @ap!  We'll likely upgrade at $work this coming Monday.
